#!/usr/bin/python

import logging
import argparse
import os
import json
from subprocess import call

def loadConfig(location="/etc/mcfly.conf"):
    try:
        configFile = open(location)
    except IOError:
        quit("Could not open config file, exiting.")
    else:
        try:
            config = json.load(configFile)
        except ValueError:
            quit("Config file does not contain valid json, exiting.")
        else:
            return config       

parser = argparse.ArgumentParser(description='mcfly is a simple backup tool that copies folders located on remote servers to a locally defined backup folder.',
epilog=
'''Written by Martin Caarels <martin@caarels.com>
LICENSE=MIT
2017''',
formatter_class=argparse.RawTextHelpFormatter)

#parser.add_argument("-i", "--init", help="Creates a basic config file, !!WARNING!! this will overwrite a config file if there is one.", action="store_true")
parser.add_argument("-v", "--verbose", help="Increase output verbosity.", action="store_true")
parser.add_argument("-c", "--config", nargs='?', default='/etc/mcfly.conf', help="Run using alternative config file, default location is /etc/mcfly.conf.", type=loadConfig)
args = parser.parse_args()

config = args.config
logging.basicConfig(filename='mcfly.log', format='%(asctime)s %(message)s', level=logging.INFO)
if __name__ == "__main__":
    for server in config["servers"]:
        print(server)
        for dir in config["servers"][server]:
            print("\t" + dir)
    logging.info("started")
